import { Routes } from '@angular/router';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { temaPlaceholderRoutes } from '../_shared/tema-routes.helper';

@Component({
  standalone: true,
  imports: [RouterLink],
  template: `
    <h1>Selskapsmelding</h1>
    <p>Velg en SD-tema fra menylinjen ovenfor, eller åpne en hånd-/auto-generert modul under.</p>
    <p style="display:flex;gap:.5rem;flex-wrap:wrap;">
      <a routerLink="/selskapsmelding/deltager-detaljer">Åpne SD_DeltagerDetaljer (auto-generated)</a>
    </p>
  `
})
export class SelskapsmeldingPlaceholderComponent {}

const MANUAL_ROUTES: Routes = [
  { path: '', component: SelskapsmeldingPlaceholderComponent },
  {
    // Auto-generated by Cantor-Claude/dfm-to-angular from SD_DeltagerDetaljer.dfm.
    // Re-run the generator to refresh after .dfm changes.
    path: 'deltager-detaljer',
    loadComponent: () =>
      import('./sd-deltager-detaljer.component').then(m => m.SDDeltagerDetaljerComponent)
  }
];

export const SD_ROUTES: Routes = [
  ...MANUAL_ROUTES,
  // 3 SD tema routes — placeholder until real components are generated/built.
  ...temaPlaceholderRoutes('SD'),
];
